### ISSUE TITLE
Full formatted article

### ISSUE THREAD

**Issue by amigo421** [luyuhuang/vscode-rss#32] opened 2021-02-09 17:12 UTC
this is feature request.

full article loading even if it is not included into RSS record.
(if you look at inoreader, there is a "cup" icon, this functionality
suppose you have an account there, just more clear to try this than for me try to explain ) 
if you don't have such sample feed , try [this](http://arne-mertz.de/feed/) one:

default view:
![image](https://user-images.githubusercontent.com/3259933/107400658-0d806100-6b13-11eb-8ae2-07320bd506dc.png)

full view (with "cup" - full article with pics , formatting and other objects):
![image](https://user-images.githubusercontent.com/3259933/107400885-51736600-6b13-11eb-8a6b-b6f34c128703.png)

**Comment by luyuhuang** [comment] 2021-02-13 13:59
Duplicate of #24. That would be complex to implement, I am not very intended to do this. I guess the easiest way is to click "Open link" to open the origin webpage.

**Closed** 2021-02-13 16:41 UTC
